apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    role: frontend
  ports:
    - name: http
      port: 80        # Exposed port for ALB
      targetPort: 3000  # Container port
      protocol: TCP
